version: "3.6"

services:
  viact_mysql:
    image: mysql
    hostname: viact_mysql
    container_name: viact_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: viact
      MYSQL_ROOT_PASSWORD: viact_password
    command: --default-authentication-plugin=mysql_native_password

  viact_backend:
    build: ./backend
    image: viact_backend
    hostname: viact_backend
    container_name: viact_backend
    restart: always
    ports:
      - 3000:3000
    environment:
      JWT_SECRET: viact_secret
      JWT_EXPIRES: 60 #second
      MYSQL_URL: mysql://root:viact_password@viact_mysql:3306/viact
    depends_on:
      - viact_mysql

  viact_frontend:
    build: ./frontend
    image: viact_frontend
    hostname: viact_frontend
    container_name: viact_frontend
    restart: always
    ports:
      - 5173:80
    depends_on:
      - viact_backend